env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.2
    - os: osx
      language: objective-c
      osx_image: xcode7.3
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
      script:
        - . ~/.swiftenv/init
        - swift build
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
script:
  - pod lib lint --allow-warnings
  - set -o pipefail
  - xcodebuild test -scheme Himotoki-Mac -configuration Release | xcpretty -c
  - xcodebuild test -scheme Himotoki-iOS -configuration Release -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
  - xcodebuild test -scheme Himotoki-tvOS -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,name=Apple TV 1080p" | xcpretty -c
  - xcodebuild build -scheme Himotoki-watchOS -configuration Release -sdk watchsimulator -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" | xcpretty -c
notifications:
  email: false
